# Generated by Django 3.2.16 on 2022-11-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('story_image', models.ImageField(upload_to='story_images/')),
                ('summary', models.CharField(max_length=2000)),
            ],
        ),
    ]
