# Generated by Django 3.2.16 on 2022-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='summary',
        ),
        migrations.AddField(
            model_name='story',
            name='body',
            field=models.TextField(default='Default Text'),
            preserve_default=False,
        ),
    ]
