# Generated by Django 3.2.16 on 2022-11-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(default='My Trip', max_length=255),
            preserve_default=False,
        ),
    ]
