# Generated by Django 3.2.16 on 2022-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='photo1',
            field=models.ImageField(default='photo1', upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo2',
            field=models.ImageField(default='photo2', upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo3',
            field=models.ImageField(default='photo3', upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo4',
            field=models.ImageField(default='photo4', upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo5',
            field=models.ImageField(default='photo5', upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo6',
            field=models.ImageField(default='photo6', upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo7',
            field=models.ImageField(default='photo7', upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo8',
            field=models.ImageField(default='photo8', upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo9',
            field=models.ImageField(default='photo9', upload_to='trip_images/'),
            preserve_default=False,
        ),
    ]
