# Generated by Django 3.2.16 on 2023-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20221127_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='photo10',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo11',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo12',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo13',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo14',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo15',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo16',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo17',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo18',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo19',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='photo20',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
    ]
