# Generated by Django 3.2.16 on 2023-05-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20230513_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='photo10',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo11',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo12',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo13',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo14',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo15',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo16',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo17',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo18',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo19',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='photo20',
        ),
    ]
