# Generated by Django 3.2.16 on 2023-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20230513_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='photo10',
            field=models.ImageField(default=None, upload_to='trip_images/'),
            preserve_default=False,
        ),
    ]
