# Generated by Django 3.2.16 on 2023-09-29 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_remove_trip_photo10'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='photo10',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='trip_images/'),
            preserve_default=False,
        ),
    ]
